// UI Constants for VibeTunnel

export const BREAKPOINTS = {
  MOBILE: 768,
  TABLET: 1024,
  DESKTOP: 1280,
} as const;

export const SIDEBAR = {
  DEFAULT_WIDTH: 320,
  MIN_WIDTH: 240,
  MAX_WIDTH: 600,
  MOBILE_RIGHT_MARGIN: 80,
} as const;

export const TRANSITIONS = {
  SIDEBAR: 200,
  MOBILE_SLIDE: 200,
  RESIZE_HANDLE: 200,
} as const;

export const Z_INDEX = {
  MOBILE_OVERLAY: 20,
  SIDEBAR_MOBILE: 30,
  SESSION_EXITED_OVERLAY: 100,
} as const;

export const TERMINAL = {
  MIN_HEIGHT: 200,
  DEFAULT_VISIBLE_ROWS: 24,
  RESIZE_DEBOUNCE: 100,
} as const;

export const TIMING = {
  AUTO_REFRESH_INTERVAL: 3000,
  SESSION_SEARCH_DELAY: 500,
  KILL_ALL_ANIMATION_DELAY: 500,
  ERROR_MESSAGE_TIMEOUT: 5000,
  SUCCESS_MESSAGE_TIMEOUT: 5000,
  KILL_ALL_BUTTON_DISABLE_DURATION: 2000,
} as const;
